#!/bin/sh
set -eu
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE ukd_app LOGIN PASSWORD '${UKD_DB_APP_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ukd_app;
  GRANT USAGE ON SCHEMA public TO ukd_app;
EOSQL
